import React from 'react';
import './App.scss';
import MainBoard from './components/MainBoard';
import Banner from './components/Banner';
import * as backImg from './img/background';

// export default App;
export default function App() {
    // TODO: 測試用資料-畫布設定,待更新
    const canvasSettingInit = { width: 600, height: 400 };
    const [canvasSetting, setCanvasSetting] = React.useState(canvasSettingInit);
    // TODO: 測試用資料-canvas原生資料
    let canvasDataInit = {
        version: '4.2.0',
        objects: [
            {
                type: 'i-text',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 36.86,
                top: 285.19,
                width: 151.02,
                height: 93.56,
                fill: 'rgba(14, 87, 88, 0.95)',
                stroke: null,
                strokeWidth: 1,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: 0.71,
                scaleY: 0.71,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'nonzero',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                text: '測試文字\nttt',
                fontSize: 36,
                fontWeight: 'normal',
                fontFamily: 'Sans-serif',
                fontStyle: 'italic',
                lineHeight: '1.3',
                underline: false,
                overline: false,
                linethrough: false,
                textAlign: 'center',
                textBackgroundColor: '',
                charSpacing: '65',
                styles: {},
            },
            {
                type: 'rect',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 366.99,
                top: 251.33,
                width: 100,
                height: 100,
                fill: '#e89a4f',
                stroke: null,
                strokeWidth: 1,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: 1,
                scaleY: 1,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'nonzero',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                rx: 0,
                ry: 0,
            },
            {
                type: 'path',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 290.15,
                top: 44.02,
                width: 48.93,
                height: 33,
                fill: '#BADADA',
                stroke: '',
                strokeWidth: 1,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: 3.56,
                scaleY: 3.56,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'evenodd',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                path: [
                    ['M', 15.7161762, 29.0709138],
                    ['C', 22.1952751, 28.6202805, 28.1873031, 30.9919374, 31.5101065, 36.5763488],
                    ['C', 32.9698961, 39.0295401, 35.5797045, 42.4731546, 38.9354773, 41.9459529],
                    ['C', 40.9342827, 41.6320572, 42.8916982, 39.4816748, 44.4084136, 38.1412082],
                    ['C', 48.2361958, 34.7583402, 51.4264096, 27.6313586, 49.1918368, 22.7402204],
                    ['C', 47.9450443, 20.0114752, 45.6673028, 17.7994224, 42.9289372, 16.4772028],
                    ['C', 40.0229963, 15.0741418, 36.4446201, 15.5695844, 33.3750177, 14.5311183],
                    ['C', 27.2092476, 12.4451781, 20.7820934, 7.69770665, 13.9272846, 9.33844148],
                    ['C', 10.6595094, 10.1205247, 10.0444742, 11.4080979, 8.58598906, 13.9607242],
                    ['C', 7.7785922, 15.3736016, 6.89517575, 16.9915854, 5.55054214, 17.9954051],
                    ['C', 3.25074191, 19.7118999, 1.06206549, 20.5288605, 1.00063312, 23.8658797],
                    ['C', 0.939793724, 27.1870772, 5.27706135, 29.7024009, 8.24953417, 30.0436673],
                    ['C', 8.82436563, 30.1097263, 9.40809174, 30.0993324, 9.99691745, 30.0429744],
                    ['C', 11.8924263, 29.8613121, 13.8405914, 29.201415, 15.7161762, 29.0709138],
                    ['Z'],
                ],
            },
            {
                type: 'image',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 80.55,
                top: 92.05,
                width: 0,
                height: 0,
                fill: 'rgb(0,0,0)',
                stroke: null,
                strokeWidth: 0,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: null,
                scaleY: null,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'nonzero',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                cropX: 0,
                cropY: 0,
                crossOrigin: null,
                filters: [],
            },
            {
                type: 'polygon',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 27.85,
                top: 43.21,
                width: 107.02,
                height: 4.5,
                fill: '#E89A4F',
                stroke: '',
                strokeWidth: 1,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: 2.2,
                scaleY: 2.2,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'nonzero',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                points: [
                    { x: 0.0186913847, y: 10 },
                    { x: 107.018691, y: 10.5 },
                    { x: 107, y: 14.4999563 },
                    { x: 0, y: 13.9999563 },
                ],
            },
            {
                type: 'image',
                version: '4.2.0',
                originX: 'left',
                originY: 'top',
                left: 181.81,
                top: 207.6,
                width: 275,
                height: 297,
                fill: 'rgb(0,0,0)',
                stroke: null,
                strokeWidth: 0,
                strokeDashArray: null,
                strokeLineCap: 'butt',
                strokeDashOffset: 0,
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                scaleX: 0.49,
                scaleY: 0.49,
                angle: 0,
                flipX: false,
                flipY: false,
                opacity: 1,
                shadow: null,
                visible: true,
                backgroundColor: '',
                fillRule: 'nonzero',
                paintFirst: 'fill',
                globalCompositeOperation: 'source-over',
                skewX: 0,
                skewY: 0,
                cropX: 0,
                cropY: 0,
                src: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg',
                crossOrigin: 'anonymous',
                filters: [],
            },
        ],
        background: '#fff',
    };

    const [canvasData, setCanvasData] = React.useState(canvasDataInit);
    // settings for canvas and elements inside
    const drawingAreaSettings = {
        canvasSetting,
        setCanvasSetting,
        canvasData,
        setCanvasData,
        canvasSetting,
        setCanvasSetting,
    };

    const Background = () => {
        return (
            <div className='backImages'>
                <backImg.BackY1 className='backImg backY1' />
                <backImg.BackY2 className='backImg backY2' />
                {/* <backImg.BackY3 className='backImg' /> */}
                <backImg.BackW1 className='backImg backW1' />
                <backImg.BackW2 className='backImg backW2' />
                <backImg.BackW3 className='backImg backW3' />
                <backImg.BackW4 className='backImg backW4' />
                <backImg.BackG1 className='backImg backG1' />
                <backImg.BackG2 className='backImg backG2' />
                <backImg.BackL1 className='backImg backL1' />
                <backImg.BackL2 className='backImg backL2' />
            </div>
        );
    };

    // render
    return (
        <div className='App'>
            <Background />
            <Banner />
            <MainBoard drawingAreaSettings={drawingAreaSettings} />
        </div>
    );
}
